// // @ts-check

// // This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.

//  @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
//  */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

// export default sidebars;

// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
 const sidebars = {
  // ✅ Keep tutorial sidebar for tutorial content only
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorial-basics' }],

  // ✅ Separate sidebar for Admin
  adminSidebar: [
    {
      type: 'category',
      label: 'Admin',
      items: [
        'admin/introduction',
        'admin/configuration',
        'admin/manage-users',
        'admin/security',
        'admin/Executive-Management',
        'admin/api-key-management',
        'admin/call-recording-setting'
      ],
    },
  ],

  // ✅ Separate sidebar for User
  userSidebar: [
    {
      type: 'category',
      label: 'User',
      items: [
        'user/getting-started',
        'user/features',
        'user/settings',
        'user/troubleshooting',
      ],
    },
  ],

  // ✅ Separate sidebar for API Documentation
  apiSidebar: [
    {
      type: 'category',
      label: 'API Documentation',
      items: [
        'api/authentication',
        'api/endpoints',
        'api/examples',
        'api/error-handling',
      ],
    },
  ],
  campaignSidebar: [
    {
      type: 'category',
      label: 'campaign Documentation',
      items: [
         'campaign/introduction',
        'campaign/audio-file-manager'
      ],
    },
  ],
};
export default sidebars;
