// // @ts-check

// // This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.

//  @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
//  */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

// export default sidebars;

// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
 const sidebars = {
  // ✅ Tutorial Sidebar
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorial-basics' }],

  // ✅ Admin Sidebar with Nested Campaign Section
  adminSidebar: [
    {
      type: 'category',
      label: 'Admin',
      collapsed: false, // Expand Admin by default
      items: [
        {
          type: 'category',
          label: 'Admin Management',
          collapsed: true, // Collapse Admin Management by default
          items: [
             'admin/introduction',
            // 'admin/configuration',
            // 'admin/manage-users',
            // 'admin/security',
            'admin/Executive-Management',
            'admin/api-key-management',
            'admin/call-recording-setting',
            'admin/User-Management',
            'admin/Recharge Management',
            'admin/language preference',
            'admin/sms and whatsapp account',
            'admin/cli number setting',
          ],
        },
        
        // 🚩 Nested Campaign Section as a Subcategory under Admin
        {
          type: 'category',
          label: 'Campaign',
          collapsed: true, // Collapse Campaign by default
          items: [
            'campaign/introduction',
            'campaign/audio-file-manager',
            'campaign/black-list manager',
            'campaign/agent contact manager',
            'campaign/campaign-management'
          ],
        },
        {
          type: 'category',
          label: 'Report',
          collapsed: true, // Collapse Campaign by default
          items: [
            'report/invalid numbers report',
            'report/inbound call report',
            'report/duplicates contact report',
            'report/Call flow Error Report',
            'report/outbound call report',
            'report/SMS and Whatsapp Report',
            'report/aggregate analytic report'
          ],
        },
      ],
    },
  ],
  // ✅ User Sidebar
  userSidebar: [
    {
      type: 'category',
      label: 'User',
      items: [
        'user/getting-started',
        'user/features',
        'user/settings',
        'user/troubleshooting',
      ],
    },
  ],

  // ✅ API Documentation Sidebar
  apiSidebar: [
    {
      type: 'category',
      label: 'API Documentation',
      items: [
        'api/authentication',
        'api/endpoints',
        'api/examples',
        'api/error-handling',
      ],
    },
  ],
};

export default sidebars;
